name: WR602

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Move in webapp
      run: |
        cd webapp/
        ls
        pwd
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.local') || copy('.env.test', '.env.local');"
    - name: Install Dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
    - name: Create Database
      run: |
        mkdir -p data
        touch data/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
      run: vendor/bin/phpunit tests/
    - name: Execute CodeSniffer
      run: vendor/bin/phpcs --standard=PSR2 src/
    - name: Execute PhpStan
      run: vendor/bin/phpstan analyze src/
    - name: Execute PhpMd
      run: vendor/bin/phpmd src/ text cleancode,codesize,controversial
